config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :new, :create, :edit, :update, :show]
  resources :projects do
    resources :pledges, only: [:new, :create, :index]
  end
  resources :pledges, only: [:destroy]
  

  root to: 'static#home'
  get '/login' => 'sessions#login'
  post 'log' => 'sessions#log'
  post '/logout' => 'sessions#logout'
  match '/auth/:google_oauth2/callback' => 'sessions#google', via: [:get,:post]
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :state, optional: true
  belongs_to :community, optional: true
  has_many :pledges
  has_many :projects, through: :pledges

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  
  has_secure_password
  accepts_nested_attributes_for :community

  def community_attributes=(params)
    @community = Community.where(:state_id => self.state_id, :location => params[:location].downcase).first_or_create
    self.community = @community
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :redirect_if_not_logged_in, only: [:show, :edit, :update]

  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in_user
      redirect_to edit_user_path(@user)
    else
      full_error_messages(@user)
      render :new
    end
  end

  def show
    @user = current_user
    @lead_projects = Project.user_organized_projects(@user.id)
    @projects = @lead_projects + @user.projects
    @user_pledges = Pledge.ordered_user_pledges(@user.id)
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.state_id = user_params[:state_id]
    @user.update(user_params)
    if @user.save
      redirect_to root_path
    else
      full_error_messages(@user)
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :state_id, community_attributes: [:location])
  end

end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/edit.html.erb
<div class="center-align">
  <h1>Update Your Location</h1>
</div>

<div class="container row">
  <div  class="col s8 offset-s2">
  <%= form_for @user do |f| %>
  <h3>State</h3>
    <%= f.collection_select :state_id, State.all, :id, :name, include_blank: "Select State" %>
    <br>
  <h3>Community</h3>
    <%= f.fields_for :community, @user.build_community do |b| %>
      <%= b.label "City or Township" %> <br>
      <%= b.text_field :location %>
    <% end %>
    <br>
    <br>
  <%= f.submit "Update Location", :class => "btn green lighten-1 white-text" %>
  <% end %>
  </div>
</div>

<script>$(document).ready(function(){
    $('select').formSelect();
  });</script>

app/views/users/index.html.erb
<h1>Hello World!</h1>

<%if session[:user_id]%>
  <%= current_user.name %>
<%end%>

app/views/users/new.html.erb
<div class="header container center-align">
<h1>Sign Up</h1>
</div>


<div class="container row">
  <div class="col s8 offset-s2">
    <%= form_for @user do |f| %>
      <div>
        <%= f.label :name %> <br>
        <%= f.text_field :name %>
      </div>
      <br>
      <div>
        <%= f.label :email %> <br>
        <%= f.email_field :email %>
      </div>
      <br>
      <div>
        <%= f.label :password %> <br>
        <%= f.password_field :password %>
      </div>
      <br>
      <%= f.submit "Create Account", :class => "btn green lighten-1 white-text" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<style>
  .div1 {
    border-bottom: 2px solid #E5E4E2;
  }
</style>



<div class="container">
  <div class="center-align">
    <h1><%= @user.name %></h1>
      <% if !@user.community.nil?%>
        <h3><%= @user.community.location_name %>, <%= @user.state.name %></h3>
      <% end %>
      <%= button_to "Update Location", edit_user_path, method: :get, :class => "btn green lighten-1 white-text"%>
  </div>
  <br>

  <div class="row">
    <div class="col s8 offset-s2">
      <%= render partial: 'projects/calender', locals: {projects: @projects}%>
    </div>
  </div>

  <br>
<div class="row">
  <div class="col s10 offset-s1">
  <ul>
    <% if !@lead_projects.empty? %>
      <h5><b>Projects you're leading</b></h5>
      <% @lead_projects.each do |p| %>
      <div class="div1">
      <li>
        <h6><%= link_to p.title, project_path(p) %>
        <%= p.readable_date %></h6>
        <br>
        <%= button_to "Edit Project", edit_project_path(p), method: :get, :class => "btn-small green lighten-1 white-text" %>
      </li>
      <br>
      </div>  
      <% end %>
    <% end %>
  <br>
  <br>
  <div>
    <% if !@user.pledges.empty? %>
    
      <h5><b>Projects you've volunteered for</b></h5>
      <% @user_pledges.each do |p|  %>
      <div class="div1">
        <li>
        <h6><%= link_to p.project.title, project_path(p.project) %>
        <%= p.project.readable_date %> <br>
        <%= p.hours%> hours pledged</h6>
        <br>
        <%= button_to "Cancel Pledge", pledge_path(p), method: :delete, :class => "btn-small red lighten-1 white-text"%>
        <br>
        </li>
      </div>  
      <% end %>
    <% end %>
  </div>
  </ul>
</div>
</div>
</div>