config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :new, :create, :edit, :update, :show]
  resources :projects do
    resources :pledges, only: [:new, :create, :index]
  end
  resources :pledges, only: [:destroy]
  

  root to: 'static#home'
  get '/login' => 'sessions#login'
  post 'log' => 'sessions#log'
  post '/logout' => 'sessions#logout'
  match '/auth/:google_oauth2/callback' => 'sessions#google', via: [:get,:post]
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :community
  has_many :pledges
  has_many :users, through: :pledges
  has_one :state, through: :community

  validates :title, presence: true
  validates :date, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :estimated_hours, presence: true
  validates :estimated_hours, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  # validates :min_volunteers, presence: true

  scope :in_date_user_projects, ->(user, today) {where('community_id = ? and date >= ?', user, today)}
  scope :user_organized_projects, ->(user_id) {where('organizer_id = ?', user_id)}


  def organizer
    User.find_by(id: self.organizer_id)
  end

  def readable_date
    self.date.strftime("%A, %B %d %Y")
  end

  def start_time
    self.date
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  before_action :redirect_if_not_logged_in
  before_action :find_project, only: [:show, :edit, :update, :destroy]
  before_action :redirect_if_not_organizer, only: [:edit, :update, :destroy]
  before_action :redirect_if_location_is_empty, only: [:new, :index]
  before_action :redirect_if_not_in_users_community, only: [:show]
  
  def index
    @projects = Project.in_date_user_projects(current_user.community.id, Date.today).order("date ASC")
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.organizer_id = current_user.id
    if @project.save
      redirect_to project_path(@project)
    else
      helpers.full_error_messages(@project)
      render :new
    end
  end

  def show
    @pledges = Pledge.project_pledges(@project.id).reverse[0,3]
    # @pledges = Pledge.where(project_id: @project.id).reverse[0,3]
  end

  def edit
  end

  def update
    @project.update(project_params)
    if @project.save
      redirect_to project_path(@project)
    else
      helpers.full_error_messages(@project)
      render :edit
    end
  end

  def destroy
    @project.pledges.destroy_all
    @project.destroy
    redirect_to new_project_path
  end

  private

  def project_params
    params.require(:project).permit(:community_id, :title, :date, :address, :description, :estimated_hours, :min_volunteers)
  end

  def find_project
    @project = Project.find_by(id: params[:id])
  end

  def redirect_if_location_is_empty
    if current_user.community.nil?
      flash[:error] = ["Update your location to proceed!"]
      redirect_to edit_user_path(current_user)
    end
  end

  def redirect_if_not_organizer
    if @project.organizer != current_user
      redirect_to user_path(current_user)
    end
  end

  def redirect_if_not_in_users_community
      if @project.community != current_user.community
        redirect_to projects_path
      end
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper

  def pledge_time_remaining(project)
    pledged_times = project.pledges.map{|pledge| pledge.hours.to_i}
    project.estimated_hours.to_i - pledged_times.sum
  end

  def total_pledge_time(project)
    project.pledges.map{|pledge| pledge.hours.to_i}.sum
  end


  def already_pledged?(project, user)
    pledge = Pledge.where(project_id: project.id, user_id: current_user.id)
    !pledge.empty?
  end

  def reformat_old_projects
    @projects = Project.where('date < ?', "#{Date.today}")
    @projects.each do |p|
      p.pledges.destroy_all
      p.save
    end
  end

end

app/views/projects/_calender.html.erb
  <%= month_calendar(events: projects) do |date, projects| %>
    <%= date.day %>
    <%if !projects.nil? %>
      <% projects.each do |project| %>
        <div>
          <%= link_to project.title, project_path(project) %>
          <br><br>
        </div>
      <% end %>
    <% end %>
  <% end %>

app/views/projects/_form.html.erb
<div class="container row">
  <div  class="col s8 offset-s2">

<%= form_for project do |f| %>
<%= f.hidden_field :community_id, value: current_user.community.id %>
  <br>
  <%= f.label :title %> <br>
  <%= f.text_field :title %>
  <br>
  <br>
  <%= f.label :date %> <br>
  <%= f.date_field :date %>
  <br>
  <br>
  <%= f.label "Estimated Hours Needed" %> <br>
  <%= f.text_field :estimated_hours %>
  <br>
  <br>
  <%= f.label :address %> <br>
  <%= f.text_field :address %>
  <br>
  <br>
  <%= f.label :description %> <br>
  <%= f.text_area :description, :class => "materialize-textarea" %>
  <br>
  <br>
  <%= f.submit button_name, :class => "btn green lighten-1 white-text" %>
<% end %>

  </div>
</div>

app/views/projects/_options.html.erb
<% if is_logged_in? %>
  <% if current_user == project.organizer %>
    <%= button_to "Edit Project", edit_project_path(project), method: :get, :class => "btn-large blue lighten-2" %>
    <br>
  <% elsif already_pledged?(project, current_user) %>
    <h5 class="center-align">Thank you for pledging your time to this Project!</h5>
    <br>
  <% elsif project.state == current_user.state %>
    <b><%= button_to "Volunteer Now", new_project_pledge_path(project), method: :get, :class => "btn-large yellow darken-1 black-text"%></b>
  <%end%>
<%end%> 

app/views/projects/_pledge_form.html.erb
  
<div class="container row">
  <div class="col s8 offset-s2">
      <%= form_tag ({controller: 'pledges', action: 'create', method: 'post'}) do %>
        <label>Hours: </label>
        <input type=text name=pledge_hours size="1">
        <input type=submit value='Pledge Your Time!'>
      <%end%>
  </div>
</div>

app/views/projects/_pledges.html.erb
<style>
  .div1 {
    border-bottom: 1px solid #E5E4E2;
  }

  .icon {
    position: relative;
    top: 7px;
    left: 5px;
  }
</style>

<ul>
  <li>
    <% pledges.each do |pledge| %>
      <div class="div1">
        <i class="icon small material-icons" style="color:green">person &ensp;</i> <%= pledge.user.name %> pledged <%= pledge.hours%> hours <%= pledge.created_at.strftime("-%b %d") %> <br>
        <br>
      </div>
      <br>
    <% end %>
  </li>
</ul>

app/views/projects/edit.html.erb
<div class="center-align">
  <h1>Edit Project Page</h1>
<%= button_to "Delete Project", project_path(@project), method: :delete, :class => "btn red"%>
</div>

<%= render partial: 'form', locals: {project: @project, button_name: "Update Project"}%>

app/views/projects/index.html.erb
<style>
  .calender {
    padding: 40px, 0px, 80px, 0px;
  }
</style>

<div class="container row">
    <div class="col s8 offset-s2">
    <h1 class="center-align">Projects in <%= current_user.community.location_name %></h1>
      <%= render partial: 'projects/calender', locals: {projects: @projects}%>
    </div>
</div>   

<div class="container row">
  <div class ="col s10 offset-s1">


    <ul>
      <% @projects.each do |project| %>
      <div class="card-panel m4">
        <h5 class="center-align"><%=link_to project.title, project_path(project)%></h5>
        <h6><%= project.community.location.capitalize %>, <%= project.state.name %></h6>
        <h6><%= project.readable_date %></h6>
        <!-- <h6><%= project.pledges.length %>/<%= project.min_volunteers %> volunteers commited</h6> -->
        <h6><%= project.pledges.length%> pledges</h6>
        <% if pledge_time_remaining(project) > 0 %>
          <h6><%= pledge_time_remaining(project)%> pledged-hours until goal met</h6>
        <% else %>
          <h6>Pledge Goals have been met!</h6>
        <% end %>
      </div>
      <%end%>
    </ul>

  </div>
</div>

app/views/projects/local.html.erb
<h1>Projects in Your Area</h1>

<ul>
  <% @projects.each do |project| %>
    <li><h2><%=link_to project.title, project_path(project)%></h2></li>
  <%end%>
</ul>

app/views/projects/new.html.erb
<div class="container center-align">
  <h1><%= current_user.name %>'s New Project</h1>
  <h3><%=current_user.community.location.capitalize %>, <%=current_user.state.name %></h3>
</div>
<%= render partial: 'form', locals: {project: @project, button_name: "Create Project"}%>

app/views/projects/show.html.erb
<style>

  .fixedContainer {
    background-color:#ddd;
    position: fixed;
    padding: 2em;
    left: 69%;
    top: 25%;
    transform: translateX(-50%);
}

  .sideStatus {
    background-color: white;
    radius: 2px;
    padding: 10px, 10px, 10px, 10px;
    box-shadow: 1px 1px 9px 5px #E5E4E2
  }

  .projectTitle {
    text-align: center;
    padding-bottom: 50px;
  }

  .div1 {
    border-bottom: 1px solid #E5E4E2;
  }

  .description {
    padding: 0px, 20px, 0px, 0px
  }

</style>


<div class="container row">
  <div class="projectTitle">
    <h1><b><%= @project.title%></b></h1>
    <h5><%= @project.community.location.capitalize %>, <%= @project.state.name %></h5>
  </div>

  
  <div class="col s4 offset-s1">
    <h4>Project description</h4>
    <h6><%= @project. description %></h6>
    <h6>Estimated Hours Needed: <%= @project.estimated_hours %></h6>
    <br>
    <h4>When/Where</h4>
    <h6><%= @project.date.strftime("%A, %B %d %Y")%></h6>
    <h6><%= @project.address %></h6>
    <br>
    <h6>Organizer: <%= @project.organizer.name %></h6>
    <h6>Organizer email: <%= @project.organizer.email %></h6>
    <br>
  </div>
  
  
  <div class="sideStatus col s5 offset-s1 center-align">
    <br>
    <% if pledge_time_remaining(@project) > 0 %>
      <h6><b><%= pledge_time_remaining(@project)%> pledged-hours left until we reach our goal</b></h6>
      <progress value=<%=total_pledge_time(@project)%> max=<%= @project.estimated_hours %>></progress>
    <% else %>
      <h6><b>Volutnteer hours goal has been met!!!</b></h6>
      <progress value=<%=total_pledge_time(@project)%> max=<%= @project.estimated_hours %>></progress>
    <% end %>
    <!-- <h6><b><%= @project.pledges.length %>/<%= @project.min_volunteers %> Volunteers Commited!</b></h6>
    <progress value=<%=@project.pledges.length%> max=<%= @project.min_volunteers %>></progress> -->
    <br>
    <br>
      <%= render partial: 'options', locals: {project: @project} %>
    <br>
    <h6 class="purple-text text-lighten-2"><b><%= @project.date.mjd - Date.today.mjd %> days left until project date!</b></h6>
    <br>
    <h6><b>Recent Activity</b></h6>
    <h6 class="left-align"><%= render partial: 'pledges', locals: {pledges: @pledges} %></h6>
    <% if @project.pledges.length > 3 %>
      <%= button_to "View All Pledges", project_pledges_path(@project), method: :get, :class => "btn green lighten-1 white-text"%>
    <% end %>
    <br>
  </div>
  

</div>

<div class="container row">
  <div class="col s8 offset-s2">
 
  <div class="div1">
    <h4>Activity(<%= @project.pledges.length %>)</h4>
  </div>

    <ul>
      <h6><%= render @pledges %></h6>
    </ul>

    <% if @project.pledges.length > 3 %>
    <div class="center-align">
      <%= button_to "View All Pledges", project_pledges_path(@project), method: :get, :class => "btn green lighten-1 white-text"%>
    </div>
    <% end %>

  </div>
</div>