config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :new, :create, :edit, :update, :show]
  resources :projects do
    resources :pledges, only: [:new, :create, :index]
  end
  resources :pledges, only: [:destroy]
  

  root to: 'static#home'
  get '/login' => 'sessions#login'
  post 'log' => 'sessions#log'
  post '/logout' => 'sessions#logout'
  match '/auth/:google_oauth2/callback' => 'sessions#google', via: [:get,:post]
end

app/views/layouts/_errors.html.erb
<div class="container errors red-text">
  <% if flash[:error] %>
    <% flash[:error].each do |error| %>
      <p><%= error %></p>
    <%end%>
  <%end%>
</div>
  <%= flash[:notice] if flash[:notice] %>

app/views/layouts/_nav.html.erb
  <style>    
    nav ul li a{
      color: black;
    }    
  </style>
  
<div class="navbar-fixed container">
  <nav class="container white">
    <div class="nav-wrapper">
    <b><a href="/" class="brand-logo center green-text bold">Go Local!</a></b>
    <%if !is_logged_in? %>
    <ul class="left black-text">
      <li><%= link_to "Home", root_path %></li>
    </ul>
    <ul class="right black-text">
      <li><%= link_to "Signup", new_user_path %></li>
      <li><%=link_to "Login", login_path %></li>
      <li><%= link_to "Log in with Google", '/auth/google_oauth2', method: :post %></li>
    </ul>
    <% else %>
    <ul class="left black-text">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Local Projects", projects_path %> </li>
    </ul>
    <ul class="right black-text">
      <li><%= link_to "Create Project", new_project_path %> </li>
      <li><%= link_to "My Stuff", user_path(current_user) %> </li>
      <!-- <li><%= link_to "Edit My Info", edit_user_path(current_user) %></li> -->
      <li><%= link_to "Logout", logout_path, method: :post %></li>
    </ul>
    <%end%>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Volunteer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Makes collection_for useable with materialize -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <!-- Materialize Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
            
  </head>

  <body>
  <%= render 'layouts/nav' %>
  <%= render 'layouts/errors' %>

    <%= yield %>
  </body>
</html>